import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

// Define the Arabic font
const arabic = localFont({
  src: "../public/fonts/BismillahScript.ttf",
  variable: "--font-arabic", // Optional: Define a CSS variable for better control
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${arabic.variable} antialiased`} // Use arabic.variable instead of arabic.className
      >
        {children}
      </body>
    </html>
  );
}
